### ISSUE TITLE
Detection accuracy in paper

### ISSUE THREAD

**Issue by katjaschwarz** [sutd-visual-computing-group/Fourier-Discrepancies-CNN-Detection#2]
Hi,

thanks for this interesting work and the code base!
I am wondering, for the detection accuracy you report (e.g. in table 2 in the paper), how is this computed precisely? It cannot be classification accuracy because otherwise the minimum value would be ~50% (chance for two classes), no?

Cheers,
Katja

**Comment by keshik6** [comment]
Hi Katja,
Thanks for the question.

Table 2 shows the detection/ bypass rates using the classifier trained using real and GAN images, where GAN images correspond to the Baseline/ Transpose convolution setup. 

So, 1) If this classifier is perfect, then the detection accuracy should be 100% (all GAN images in table 2 are successfully classified as fake). 2) Worse case all GAN images in table 2 will be classified as real which means the detection rate is 0%.

Hope this answers your question. 

You can also refer to Supplementary (Section F) for more details on Classifier implementation.

Thanks

Regards,
Keshik

**Comment by katjaschwarz** [comment]
Hi Keshik,

I see, so it is the accuracy only on the fake images, thanks for the quick reply! :)
But in this case wouldn't a classifier that simply predicts 'fake' for all of the test samples (including both real and fake images) also be a 'perfect' classifier as this will produce 100% in your setting?
What was the motivation to report this scores other than the accuracy on both real and fake images?

Yes, I looked at the suppmat already and it was super helpful, thanks a lot for the detailed description!

Best,
Katja

**Comment by keshik6** [comment]
Yes, I agree with the fact that a simple classifier that will always predict 'fake' can work well wrt to Table 2, although it will classify all real images as fake as well. (This is not very useful)

Fyi, all these classifiers have near perfect accuracy in detecting both real and fake images from the test set similar to Dzanic et. al (fake images correspond to transpose convolution setups). These results were not reported in the paper since I thought it was trivial.

The goal of this work is to study whether high frequency spectral decay discrepancies are intrinsic (We observe that these discrepancies can be avoided). Therefore we further evaluate the robustness of classifiers leveraging on high frequency spectral decay features for synthetic image detection. (This is the motivation for Table 2)

Hope this answers your question.

Thanks

**Comment by katjaschwarz** [comment]
Okay, thank you for your explanation! :)

**Comment by keshik6** [comment]
Closing this issue, feel free to reopen.
